# (...)

recorder:

  purge_keep_days: 8
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_clock
      - sensor.eb3_clock
      - sensor.eb5_clock
    entity_globs:
      - sensor.eb1_0x*
###

utility_meter:

  daily_energy_eb1:
    source: sensor.eb1_total_energy_import
    cycle: daily

  daily_energy_eb3:
    source: sensor.eb3_total_energy_import
    cycle: daily

###

  monthly_eb3_t1:
    source: sensor.eb3_total_energy_t1_vazio
    cycle: monthly

  monthly_eb3_t2:
    source: sensor.eb3_total_energy_t2_ponta
    cycle: monthly

  monthly_eb3_t3:
    source: sensor.eb3_total_energy_t3_cheias
    cycle: monthly

###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

#sensor eb1tas: !include files/tasmota-eb1.yaml
#sensor eb2tas: !include files/tasmota-eb2.yaml
sensor eb3tas: !include files/tasmota-eb3.yaml
#sensor eb1esp: !include files/esphome-eb1.yaml

###

modbus: !include files/modbus.yaml
sensor eb1mod: !include files/modbus-eb1.yaml

###
##
#
