# /config/configuration.yaml

#default_config:

###
# https://github.com/home-assistant/core/blob/dev/homeassistant/components/default_config/manifest.json

automation:
#cloud:
counter:
dhcp:
energy:
frontend:
history:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
#media_source:
mobile_app:
my:
network:
person:
scene:
script:
ssdp:
sun:
system_health:
tag:
timer:
updater:
webhook:
zeroconf:
zone:

###
###

logger:

  logs:
    homeassistant.components.modbus: debug
    pymodbus.client: debug

homeassistant:

  customize: !include files/customize.yaml

http:

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16

recorder:

  purge_keep_days: 8
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_clock
      - sensor.eb3_clock
    entity_globs:
      - sensor.eb1_0x*
      - sensor.eb3_clock*
###

utility_meter:

  utm_eb3_import:
    name: UTM EB3 Import
    source: sensor.eb3_energy_import
    cycle: daily

###

  utm_home_daily:
    name: UTM Home Daily
    source: sensor.eb3_energy_import
    cycle: daily
    tariffs:
      - Normal

  utm_home_monthly:
    name: UTM Home Monthly
    source: sensor.eb3_energy_import
    cycle: monthly
    tariffs:
      - Normal

###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

#sensor eb1tas: !include files/tasmota-eb1.yaml
#sensor eb2tas: !include files/tasmota-eb2.yaml
sensor eb3tas: !include files/tasmota-eb3.yaml
#sensor eb3esp: !include files/esphome-eb3.yaml

###

modbus: !include files/modbus.yaml
sensor eb1mod: !include files/modbus-eb1.yaml

###

sensor integral: !include files/integral.yaml

###
##
#
