# (...)

recorder:

  purge_keep_days: 40
  # external db recommended
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8

utility_meter:

  daily_energy_eb1:
    source: sensor.eb1_total_energy_import
    cycle: daily

  daily_energy_eb2:
    source: sensor.eb2_total_energy_import
    cycle: daily

sensor edpbox1a: !include tasmota-eb1a.yaml
sensor edpbox1b: !include tasmota-eb1b.yaml
sensor eb2mono: !include tasmota-eb2mono.yaml
#sensor eb1esphm: !include esphome-eb1.yaml
#sensor modbus1eb: !include modbus-eb1.yaml

###
##
#
