# /config/configuration.yaml

default_config:

#automation: !include automations.yaml

#notify:
#  - name: loadprofile
#    platform: file
#    filename: /config/loadprofile-1.csv
#    timestamp: true

#logger:
#  logs:
#    homeassistant.components.modbus: debug
#    pymodbus.client: debug
#    custom_components.modbus.modbus: debug

homeassistant:

  customize: !include files/customize.yaml

http:

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16

recorder:

  purge_keep_days: 8
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_esp_clock
      - sensor.eb3_esp_clock
    entity_globs:
      - sensor.eb1_0x*
      - sensor.eb1_clock*
      - sensor.eb3_clock*
###

utility_meter:

  utm_eb3_daily1:
    source: sensor.eb3_import
    cycle: daily

  utm_eb3_weekly:
    source: sensor.eb3_import
    cycle: weekly

  utm_eb3_monthly:
    source: sensor.eb3_import
    cycle: monthly

###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

sensor eb1tas: !include files/tasmota-eb1.yaml
#sensor eb3tas: !include files/tasmota-eb3.yaml
#sensor eb3esp: !include files/esphome-eb3.yaml

###

modbus: !include files/modbus.yaml
template: !include files/modbus-eb3.yaml

#sensor eb1mod: !include files/modbus-eb1.yaml

###

sensor integral: !include files/integral.yaml

###

switch:

  - platform: mqtt
    name: "EB1 ESP Restart"
    state_topic: "tele/edpbox1/LWT"
    command_topic: "cmnd/edpbox1/restart"
    availability_topic: "tele/edpbox1/LWT"
    payload_on: "1"
    payload_available: "Online"
    payload_not_available: "Offline"

#  - platform: mqtt
#    name: "EB3 ESP Restart"
#    state_topic: "tele/edpbox3/LWT"
#    command_topic: "cmnd/edpbox3/restart"
#    availability_topic: "tele/edpbox3/LWT"
#    payload_on: "1"
#    payload_available: "Online"
#    payload_not_available: "Offline"

###

sensor monitor:

  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: processor_use

###
##
#
