# (...)

recorder:

  purge_keep_days: 5
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_clock
      - sensor.eb2_clock
    entity_globs:
      - sensor.eb1_0x*
###

utility_meter:

  daily_energy_eb1:
    source: sensor.eb1_total_energy_import
    cycle: daily

  daily_energy_eb2:
    source: sensor.eb2_total_energy_import
    cycle: daily

###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

sensor eb1tas: !include tasmota-eb1tri.yaml
#sensor eb2tas: !include tasmota-eb2mono.yaml
#sensor eb1esp: !include esphome-eb1.yaml
#sensor eb1mod: !include modbus-eb1.yaml

###

modbus: !include modbus-base.yaml

###
##
#
