# (...)

recorder:

  purge_keep_days: 2
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8

utility_meter:

  daily_energy_eb1:
    source: sensor.eb1_total_energy_import
    cycle: daily

  daily_energy_eb2:
    source: sensor.eb2_total_energy_import
    cycle: daily

#sensor edpbox1a: !include edpbox1a.yaml
#sensor edpbox1b: !include edpbox1b.yaml
sensor eb2mono: !include eb2mono.yaml


###
##
#
