# /config/configuration.yaml

default_config:

#automation: !include automations.yaml

#notify:
#  - name: loadprofile
#    platform: file
#    filename: /config/loadprofile-1.csv
#    timestamp: true

#logger:
#  logs:
#    homeassistant.components.modbus: debug
#    pymodbus.client: debug
#    custom_components.modbus.modbus: debug

homeassistant:

  customize: !include customize.yaml
  packages:
    eb1tasmota: !include pkg/eb1tasmota.yaml
    #eb3modbus: !include pkg/eb3modbus.yaml
    eb3tasmota: !include pkg/eb3tasmota.yaml

http:

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16

recorder:

  purge_keep_days: 8
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_esp_clock
      - sensor.eb3_esp_clock
    entity_globs:
      - sensor.eb1_0x*
      - sensor.eb3_0x*
      - sensor.eb1_clock*
      - sensor.eb3_clock*
###

utility_meter:

  utm_eb3_daily1:
    source: sensor.eb3_import
    cycle: daily

  utm_eb3_weekly:
    source: sensor.eb3_import
    cycle: weekly

  utm_eb3_monthly:
    source: sensor.eb3_import
    cycle: monthly

###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

sensor integral: !include integral.yaml

###

sensor monitor:

  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: processor_use

###

sensor cmd:

  - platform: command_line
    name: CMD Date
    command: "date"
    unit_of_measurement: ""
    value_template: "{{ value|string }}"

###
##
#
