# /config/configuration.yaml

default_config:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

#notify:
#  - name: loadprofile
#    platform: file
#    filename: /config/loadprofile-1.csv
#    timestamp: true

#logger:
#  logs:
#    homeassistant.components.modbus: debug
#    pymodbus.client: debug
#    custom_components.modbus.modbus: debug

homeassistant:

  customize: !include customize.yaml
  packages:
    eb1tasmota: !include pkg/eb1tasmota.yaml
    #eb3modbus: !include pkg/eb3modbus.yaml
    eb3tasmota: !include pkg/eb3tasmota.yaml
    private: !include pkg/private.yaml

http:

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16

recorder:

  purge_keep_days: 3
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_esp_clock
      - sensor.eb3_esp_clock
    entity_globs:
      - sensor.eb1_0x*
      - sensor.eb3_0x*
      - sensor.eb1_clock*
      - sensor.eb3_clock*
###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

sensor integral: !include integral.yaml

###

sensor monitor:

  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: processor_use

###

#utility_meter:

# example for erse users

#  utm_mensal:
#    source: sensor.eb3_import
#    cycle: monthly
#    tariffs:
#      - Fora de Vazio
#      - Vazio

#  utm_diario:
#    source: sensor.eb3_import
#    cycle: daily
#    tariffs:
#      - Fora de Vazio
#      - Vazio

###

climate:

  - platform: generic_thermostat
    name: Heat P1 7C
    heater: switch.athom_p1
    target_sensor: sensor.mho_7c_temp
    min_temp: 15
    max_temp: 21
    ac_mode: false
    target_temp: 18.5
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 2
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1

  - platform: generic_thermostat
    name: Heat P1 GN
    heater: switch.athom_p1
    target_sensor: sensor.mmc_33_temp
    min_temp: 15
    max_temp: 21
    ac_mode: false
    target_temp: 18.5
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 2
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1

###

generic_hygrostat:

  - name: Humi P1 GN
    humidifier: switch.athom_p1
    target_sensor: sensor.mmc_33_hum
    min_humidity: 50
    max_humidity: 90
    target_humidity: 55
    dry_tolerance: 2
    wet_tolerance: 2
    device_class: "dehumidifier"
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_state: false
    away_humidity: 50
    away_fixed: true
    sensor_stale_duration: 01:15:00

###

###
##
#

