# /config/configuration.yaml

default_config:

automation: !include automations.yaml

#logger:
#  logs:
#    homeassistant.components.modbus: debug
#    pymodbus.client: debug

homeassistant:

  customize: !include files/customize.yaml

http:

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16

recorder:

  purge_keep_days: 8
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_clock
      - sensor.eb3_clock
    entity_globs:
      - sensor.eb1_0x*
      - sensor.eb3_clock*
###

utility_meter:

  utm_eb3_daily1:
    source: sensor.eb3_import
    cycle: daily

  utm_eb3_weekly:
    source: sensor.eb3_import
    cycle: weekly

  utm_eb3_monthly:
    source: sensor.eb3_import
    cycle: monthly

  utm_eb3_yearly:
    source: sensor.eb3_import
    cycle: yearly

###

  utm_upac_import:
    source: sensor.eb3_import
    cycle: quarter-hourly

###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

#sensor eb1tas: !include files/tasmota-eb1.yaml
#sensor eb2tas: !include files/tasmota-eb2.yaml
sensor eb3tas: !include files/tasmota-eb3.yaml
#sensor eb3esp: !include files/esphome-eb3.yaml

###

modbus: !include files/modbus.yaml
sensor eb1mod: !include files/modbus-eb1.yaml

###

sensor integral: !include files/integral.yaml

###

template:
  - trigger:
      - platform: time_pattern
        hours: "*"
        minutes: 1
      - platform: time_pattern
        hours: "*"
        minutes: 16
      - platform: time_pattern
        hours: "*"
        minutes: 31
      - platform: time_pattern
        hours: "*"
        minutes: 46
    sensor:
      - name: UPAC Import
        state: >
          {% set a = state_attr('sensor.utm_upac_import', 'last_value')|float %}
          {% set b = states('sensor.upac_import')|float %}
            {{ a + b }}
        unit_of_measurement: "kWh"

###
##
#
