# ha config

counter:
dhcp:
energy:
frontend:
history:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
#media_source:
mobile_app:
my:
network:
person:
ssdp:
#sun:
system_health:
#tag:
timer:
updater:
webhook:
zeroconf:
zone:

# default yaml

group: !include groups.yaml
automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

# (...)

#logger:
#
#  logs:
#    homeassistant.components.modbus: debug
#    pymodbus.client: debug

homeassistant:

  customize: !include customize.yaml

http:

  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16

recorder:

  purge_keep_days: 8
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  exclude:
    entities:
      - sensor.eb1_clock
      - sensor.eb3_clock
      - sensor.eb5_clock
    entity_globs:
      - sensor.eb1_0x*
      - sensor.eb3_clock*
###

utility_meter:

###

  ez1_daily:
    source: sensor.eb3_total_energy_import
    cycle: daily
    tariffs:
      - Normal

  ez1_monthly:
    source: sensor.eb3_total_energy_import
    cycle: monthly
    tariffs:
      - Normal

  ez2_daily:
    source: sensor.eb3_total_energy_import
    cycle: daily
    tariffs:
      - Vazio
      - Fora do Vazio

  ez2_monthly:
    source: sensor.eb3_total_energy_import
    cycle: monthly
    tariffs:
      - Vazio
      - Fora do Vazio

  ez3_daily:
    source: sensor.eb3_total_energy_import
    cycle: daily
    tariffs:
      - Vazio
      - Ponta
      - Cheias

  ez3_monthly:
    source: sensor.eb3_total_energy_import
    cycle: monthly
    tariffs:
      - Vazio
      - Ponta
      - Cheias

###

  em_eb3_import:
    name: EM EB3 Import
    source: sensor.eb3_total_energy_import
    cycle: daily

  em_eb3_t1_vazio:
    name: EM EB3 T1 Vazio
    source: sensor.eb3_total_energy_t1_vazio
    cycle: daily

  em_eb3_t2_ponta:
    name: EM EB3 T2 Ponta
    source: sensor.eb3_total_energy_t2_ponta
    cycle: daily

  em_eb3_t3_cheias:
    name: EM EB3 T3 Cheias
    source: sensor.eb3_total_energy_t3_cheias
    cycle: daily

###

sensor mariadb:

- platform: sql
  db_url: mysql://hassio:hassio@10.1.0.71/homeassistant?charset=utf8
  queries:
    - name: "DB Size MB"
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / (1024 * 1024), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: "MB"

###

#sensor eb1tas: !include files/tasmota-eb1.yaml
#sensor eb2tas: !include files/tasmota-eb2.yaml
sensor eb3tas: !include files/tasmota-eb3.yaml
#sensor eb1esp: !include files/esphome-eb1.yaml

###

modbus: !include files/modbus.yaml
sensor eb1mod: !include files/modbus-eb1.yaml

###

sensor integral:

  - platform: integration
    source: sensor.eb3_active_power_l1
    name: EM EB3 L1
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.eb3_active_power_l2
    name: EM EB3 L2
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.eb3_active_power_l3
    name: EM EB3 L3
    unit_prefix: k
    round: 2

###
##
#
