# sensor:

  - platform: mqtt
    name: "EB ESP Uptime"
    unique_id: eb_esp_uptime
    state_topic: "tele/contador/STATE"
    value_template: '{{ ( value_json.UptimeSec / 3600 ) | round(1) }}'
    unit_of_measurement: "h"
    icon: mdi:alarm

  - platform: mqtt
    name: "EB ESP Signal"
    unique_id: eb_esp_signal
    state_topic: "tele/contador/STATE"
    value_template: '{{ value_json.Wifi.Signal }}'
    unit_of_measurement: "dBm"
    icon: mdi:signal

  - platform: mqtt
    name: "EB Clock"
    unique_id: ebclock
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Clock_H }}:{{ value_json.EB.Clock_M }}:{{ value_json.EB.Clock_S }}'
    icon: mdi:clock

  - platform: mqtt
    name: "EB Tensão L1"
    unique_id: ebten1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L1 > 0 %}
        {{ value_json.EB.Voltage_L1 }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Tensão L2"
    unique_id: ebten2
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L2 > 0 %}
        {{ value_json.EB.Voltage_L2 }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Tensão L3"
    unique_id: ebten3
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L3 > 0 %}
        {{ value_json.EB.Voltage_L3 }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Corrente L1"
    unique_id: ebcur1
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L1 }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L2"
    unique_id: ebcur2
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L2 }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L3"
    unique_id: ebcur3
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L3 }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Factor de Potência"
    unique_id: ebpfactor
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor_P1 > 0.1 %}
        {{ value_json.EB.PFactor_P1 }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent
 
  - platform: mqtt
    name: "EB Potência Activa"
    unique_id: ebpowerp1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_P1 > 0 %}
        {{ value_json.EB.Power_P1 }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Potência Pico"
    unique_id: ebpowerp1max
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_Max_P1 > 0 %}
        {{ value_json.EB.Power_Max_P1 }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Frequência"
    unique_id: ebfreq
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Frequency_P1 > 0 %}
        {{ value_json.EB.Frequency_P1 }}
      {% endif %}
    unit_of_measurement: "Hz"
    icon: mdi:current-ac
    
  - platform: mqtt
    name: "EB Consumo Vazio T1"
    unique_id: ebenergy1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_P1_R1 > 0.1 %}
        {{ value_json.EB.Energy_P1_R1 }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Consumo Ponta T2"
    unique_id: ebenergy2
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_P1_R2 > 0.1 %}
        {{ value_json.EB.Energy_P1_R2 }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Consumo Cheia T3"
    unique_id: ebenergy3
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_P1_R3 > 0.1 %}
        {{ value_json.EB.Energy_P1_R3 }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Consumo Total"
    unique_id: ebenergysum
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_P1_Sum > 0 %}
        {{ value_json.EB.Energy_P1_Sum }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Tarifa Activa"
    unique_id: ebtariff
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Tariff_P1|int == 1 %}
        {{ 'T1' }}
      {% elif value_json.EB.Tariff_P1|int == 2 %}
        {{ 'T2' }}
      {% elif value_json.EB.Tariff_P1|int == 3 %}
        {{ 'T3' }}
      {% else %}
        {{ 'Error' }}
      {% endif %}
    icon: 'mdi:counter'

