sensor edpbox:

  - platform: mqtt
    name: "EB ESP Uptime"
    unique_id: eb_esp_uptime
    state_topic: "tele/contador/STATE"
    value_template: '{{ ( value_json.UptimeSec / 3600 ) | round(1) }}'
    unit_of_measurement: "h"
    icon: mdi:alarm

  - platform: mqtt
    name: "EB ESP Signal"
    unique_id: eb_esp_signal
    state_topic: "tele/contador/STATE"
    value_template: '{{ value_json.Wifi.Signal }}'
    unit_of_measurement: "dB"
    icon: mdi:signal

  - platform: mqtt
    name: "EB Clock"
    unique_id: ebclock
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Clock_S|int }}'
    unit_of_measurement: "s"
    icon: mdi:clock

  - platform: mqtt
    name: "EB Tensão L1"
    unique_id: ebten1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L1|float > 0 %}
        {{ value_json.EB.Voltage_L1|float }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Tensão L2"
    unique_id: ebten2
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L2|float > 0 %}
        {{ value_json.EB.Voltage_L2|float }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Tensão L3"
    unique_id: ebten3
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L3|float > 0 %}
        {{ value_json.EB.Voltage_L3|float }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Corrente L1"
    unique_id: ebcur1
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L1|float }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L2"
    unique_id: ebcur2
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L2|float }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L3"
    unique_id: ebcur3
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L3|float }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Factor de Potência"
    unique_id: ebpfactor
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor|float > 0.1 %}
        {{ value_json.EB.PFactor|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent

  - platform: mqtt
    name: "EB Factor de Potência L1"
    unique_id: ebpfactorl1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor_L1|float > 0.1 %}
        {{ value_json.EB.PFactor_L1|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent

  - platform: mqtt
    name: "EB Factor de Potência L2"
    unique_id: ebpfactorl2
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor_L2|float > 0.1 %}
        {{ value_json.EB.PFactor_L2|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent

  - platform: mqtt
    name: "EB Factor de Potência L3"
    unique_id: ebpfactorl3
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor_L3|float > 0.1 %}
        {{ value_json.EB.PFactor_L3|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent

  - platform: mqtt
    name: "EB Potência Activa"
    unique_id: ebpowerp1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Power|int > 0 %}
        {{ value_json.EB.Power|int }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Potência L1"
    unique_id: ebpowerl1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_L1|int > 0 %}
        {{ value_json.EB.Power_L1|int }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Potência L2"
    unique_id: ebpowerl2
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_L2|int > 0 %}
        {{ value_json.EB.Power_L2|int }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Potência L3"
    unique_id: ebpowerl3
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_L3|int > 0 %}
        {{ value_json.EB.Power_L3|int }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Frequência"
    unique_id: ebfreq
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Frequency|float > 0 %}
        {{ value_json.EB.Frequency|float }}
      {% endif %}
    unit_of_measurement: "Hz"
    icon: mdi:current-ac
    
  - platform: mqtt
    name: "EB Consumo T1 Vazio"
    unique_id: ebenergy1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_R1|float > 0.1 %}
        {{ value_json.EB.Energy_R1|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Consumo T2 Ponta"
    unique_id: ebenergy2
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_R2|float > 0.1 %}
        {{ value_json.EB.Energy_R2|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Consumo T3 Cheia"
    unique_id: ebenergy3
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_R3|float > 0.1 %}
        {{ value_json.EB.Energy_R3|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Consumo Total"
    unique_id: ebenergysum
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_Sum|float > 0 %}
        {{ value_json.EB.Energy_Sum|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Energia Exportada"
    unique_id: ebenergyexport
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_Export|float > 0 %}
        {{ value_json.EB.Energy_Export|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Energia Q1"
    unique_id: ebenergyq1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_Q1|float > 0 %}
        {{ value_json.EB.Energy_Q1|float }}
      {% endif %}
    unit_of_measurement: "kVAr"
    icon: mdi:transmission-tower

# eof
