sensor edpbox:

  - platform: mqtt
    name: "EB ESP Status"
    unique_id: eb_esp_status
    state_topic: "tele/edpbox1/LWT"
    availability_topic: "tele/edpbox1/LWT"
    payload_available: Online
    payload_not_available: Offline
    icon: mdi:clock

  - platform: mqtt
    name: "EB ESP Uptime"
    unique_id: eb_esp_uptime
    state_topic: "tele/edpbox1/STATE"
    availability_topic: "tele/edpbox1/LWT"
    payload_available: Online
    payload_not_available: Offline
    value_template: '{{ ( value_json.UptimeSec / 3600 ) | round(1) }}'
    unit_of_measurement: "h"
    icon: mdi:clock

  - platform: mqtt
    name: "EB ESP Signal"
    unique_id: eb_esp_signal
    state_topic: "tele/edpbox1/STATE"
    availability_topic: "tele/edpbox1/LWT"
    payload_available: Online
    payload_not_available: Offline
    value_template: '{{ value_json.Wifi.Signal }}'
    unit_of_measurement: "dB"
    icon: mdi:signal

  - platform: mqtt
    name: "EB Clock"
    unique_id: ebclock
    state_topic: "tele/edpbox1/SENSOR"
    availability_topic: "tele/edpbox1/LWT"
    payload_available: Online
    payload_not_available: Offline
    value_template: '{{ value_json.EB.Clock_H|int }}:{{ value_json.EB.Clock_M|int }}:{{ value_json.EB.Clock_S|int }}'
    icon: mdi:clock

  - platform: mqtt
    name: "EB Tensão L1"
    unique_id: ebten1
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L1 > 0 %}
        {{ value_json.EB.Voltage_L1|int }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Tensão L2"
    unique_id: ebten2
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L2 > 0 %}
        {{ value_json.EB.Voltage_L2|int }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Tensão L3"
    unique_id: ebten3
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L3 > 0 %}
        {{ value_json.EB.Voltage_L3|int }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Corrente Total"
    unique_id: ebcursum
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Current_Sum > -1 %}
        {{ value_json.EB.Current_Sum|float }}
      {% endif %} 
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L1"
    unique_id: ebcur1
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Current_L1 > -1 %}
        {{ value_json.EB.Current_L1|float }}
      {% endif %} 
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L2"
    unique_id: ebcur2
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Current_L2 > -1 %}
        {{ value_json.EB.Current_L2|float }}
      {% endif %}  
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L3"
    unique_id: ebcur3
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Current_L3 > -1 %}
        {{ value_json.EB.Current_L3|float }}
      {% endif %} 
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Factor de Potência"
    unique_id: ebpfactor
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor|float > 0 %}
        {{ value_json.EB.PFactor|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent

  - platform: mqtt
    name: "EB PFactor L1"
    unique_id: ebpfactorl1
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor_L1 > 0 %}
        {{ value_json.EB.PFactor_L1|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent

  - platform: mqtt
    name: "EB PFactor L2"
    unique_id: ebpfactorl2
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor_L2 > 0 %}
        {{ value_json.EB.PFactor_L2|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent

  - platform: mqtt
    name: "EB PFactor L3"
    unique_id: ebpfactorl3
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor_L3 > 0 %}
        {{ value_json.EB.PFactor_L3|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent

  - platform: mqtt
    name: "EB Potência Activa"
    unique_id: ebpowerp1
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Power > 0 %}
        {{ value_json.EB.Power|int }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Potência L1"
    unique_id: ebpowerl1
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_L1 > -1 %}
        {{ value_json.EB.Power_L1|int }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Potência L2"
    unique_id: ebpowerl2
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_L2 > -1 %}
        {{ value_json.EB.Power_L2|int }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Potência L3"
    unique_id: ebpowerl3
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_L3 > -1 %}
        {{ value_json.EB.Power_L3|int }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug

  - platform: mqtt
    name: "EB Frequência"
    unique_id: ebfreq
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Frequency > 0 %}
        {{ value_json.EB.Frequency|float }}
      {% endif %}
    unit_of_measurement: "Hz"
    icon: mdi:current-ac
    
  - platform: mqtt
    name: "EB Energia T1 Vazio"
    unique_id: ebenergy1
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_R1 > 0 %}
        {{ value_json.EB.Energy_R1|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Energia T2 Ponta"
    unique_id: ebenergy2
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_R2 > 0 %}
        {{ value_json.EB.Energy_R2|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Energia T3 Cheia"
    unique_id: ebenergy3
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_R3 > 0 %}
        {{ value_json.EB.Energy_R3|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Energia Total"
    unique_id: ebenergysum
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_Sum > 0 %}
        {{ value_json.EB.Energy_Sum|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Energia Exportada"
    unique_id: ebenergyexport
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_Export > 0 %}
        {{ value_json.EB.Energy_Export|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Energia Q1"
    unique_id: ebenergyq1
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_Q1 > 0 %}
        {{ value_json.EB.Energy_Q1|float }}
      {% endif %}
    unit_of_measurement: "kVAr"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Energia Q4"
    unique_id: ebenergyq4
    state_topic: "tele/edpbox1/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_Q4 > 0 %}
        {{ value_json.EB.Energy_Q4|float }}
      {% endif %}
    unit_of_measurement: "kVAr"
    icon: mdi:transmission-tower

# eof
