# (...)

logger:

  logs:
    homeassistant.components.modbus: debug
    pymodbus.client: debug

modbus:

  - name: edpbox1
    type: tcp
    host: 10.1.0.53
    port: 8888
    timeout: 5
    delay: 1
  
    sensors:

      - name: "EB1 0x0001" # Clock
        slave: 1
        address: 1
        input_type: input
        count: 1
        data_type: custom
        register_size: 12
        structure: ">H7BhB"

      - name: "EB1 0x006C" # V/A
        slave: 1
        address: 108
        input_type: input
        count: 7
        data_type: custom
        structure: ">7H"

      - name: "EB1 0x0073" # Power
        slave: 1
        address: 115
        input_type: input
        count: 7
        data_type: custom
        structure: ">7L"

      - name: "EB1 0x007B" # PF
        slave: 1
        address: 123
        input_type: input
        count: 5
        data_type: custom
        structure: ">5H"


      - name: "EB1 0x000B"
        slave: 1
        address: 11
        input_type: input
        count: 1
        data_type: custom
        structure: ">Bx"

      - name: "EB1 0x0016"
        slave: 1
        address: 22
        input_type: input
        count: 2
        data_type: custom
        register_size: 4
        structure: ">2L"



# EOF
