# (...)

recorder:

  purge_keep_days: 2

utility_meter:

  daily_energy:
    source: sensor.eb_consumo_total
    cycle: daily

sensor: !include edpbox1a.yaml
sensor: !include edpbox1b.yaml

###
##
#
