# (...)

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888

    sensors:

      - name: "RTU1 X108"
        slave: 1
        address: 108
        input_type: input
        count: 7
        data_type: custom
        structure: ">7h"

      - name: "RTU1 X5"
        slave: 1
        address: 5
        input_type: input
        count: 1
        data_type: custom
        structure: ">5s"

sensor rtu1x:

  - platform: template
    sensors:

      eb1_vol_l1:
        friendly_name: "RTU1 Voltage L1"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[0] | int / 10 }}
        unit_of_measurement: "V"

      eb1_cur_l1:
        friendly_name: "RTU X Current L1"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[1] | int / 10 }}
        unit_of_measurement: "A"

# EOF
