# (...)

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888

    sensors:
        
      - name: 'RTU Voltage L1'
        slave: 1
        address: 108
        input_type: input
        count: 1
        data_type: uint
        scale: 0.1
        precision: 1
        unit_of_measurement: 'V'

      - name: 'RTU Current L1'
        slave: 1
        address: 109
        input_type: input
        count: 1
        data_type: uint
        scale: 0.1
        precision: 1
        unit_of_measurement: 'A'

      - name: 'RTU X108'
        slave: 1
        address: 108
        input_type: input
        count: 7
        data_type: custom
        structure: ">7h"

sensor rtux1:

  - platform: template
    sensors:

      Vol_L1:
        friendly_name: "RTU X Voltage L1"
        value_template: >-
          {{ states('sensor.rtu_x108').split(',')[0] | int / 10 }}
        unit_of_measurement: 'V'

      Cur_L1:
        friendly_name: "RTU X Current L1"
        value_template: >-
          {{ states('sensor.rtu_x108').split(',')[1] | int / 10 }}
        unit_of_measurement: 'A'

# EOF
