# (...)

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888

    sensors:
      - name: 'Frequency'
        hub: edpbox1
        slave: 1
        register: 127
        register_type: input
        unit_of_measurement: 'Hz'
        count: 1
        scale: 0.1
        offset: 0
        precision: 2
        # long unsigned
        data_type: uint
        
      - name: 'Voltage L1'
        hub: edpbox1
        slave: 1
        register: 108
        register_type: input
        unit_of_measurement: 'V'
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        # long unsigned
        data_type: uint

      - name: 'Current L1'
        hub: edpbox1
        slave: 1
        register: 109
        register_type: input
        unit_of_measurement: 'A'
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        # long unsigned
        data_type: uint
        
      - name: 'Power factor'
        hub: edpbox1
        slave: 1
        register: 123
        register_type: input
        unit_of_measurement: 'p.u.'
        count: 1
        scale: 0.001
        offset: 0
        precision: 3
        # long unsigned
        data_type: uint

# (...)
