# (...)

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888
    timeout: 10
    delay: 1
    scan_interval: 10

    sensors:
        
      - name: 'RTU Voltage L1'
        slave: 1
        address: 108
        input_type: input
        count: 1
        data_type: uint
        scale: 0.1
        precision: 1
        unit_of_measurement: 'V'

      - name: 'RTU Current L1'
        slave: 1
        address: 109
        input_type: input
        count: 1
        data_type: uint
        scale: 0.1
        precision: 1
        unit_of_measurement: 'A'

      - name: 'RTU Total Energy'
        slave: 1
        address: 22
        input_type: input
        count: 1
        data_type: custom
        structure: "@L"
        scale: 1
        precision: 0
        unit_of_measurement: 'kWh'

# (...)
