# (...)

logger:

  default: warn
  logs:
    homeassistan.core: debug
    homeassistant.components.modbus: debug
    pymodbus.client: debug

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888
    timeout: 5
    delay: 1

    sensors:

      - name: "RTU1 X1"
        slave: 1
        address: 1
        input_type: input
        count: 1
        data_type: custom
        structure: ">H7BhB"

      - name: "RTU1 X108"
        slave: 1
        address: 108
        input_type: input
        count: 7
        data_type: custom
        structure: ">7H"

      - name: "RTU1 X22"
        slave: 1
        address: 22
        input_type: input
        count: 1
        data_type: custom
        structure: ">L"

sensor rtu1x:

  - platform: template
    sensors:

      rtu1_vol_l1:
        friendly_name: "RTU1 Voltage L1"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[0] | int / 10 }}
        unit_of_measurement: "V"

      rtu1_cur_l1:
        friendly_name: "RTU1 Current L1"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[1] | int / 10 }}
        unit_of_measurement: "A"

      rtu1_vol_l2:
        friendly_name: "RTU1 Voltage L2"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[2] | int / 10 }}
        unit_of_measurement: "V"

      rtu1_cur_l2:
        friendly_name: "RTU1 Current L2"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[3] | int / 10 }}
        unit_of_measurement: "A"

      rtu1_vol_l3:
        friendly_name: "RTU1 Voltage L3"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[4] | int / 10 }}
        unit_of_measurement: "V"

      rtu1_cur_l3:
        friendly_name: "RTU1 Current L3"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[5] | int / 10 }}
        unit_of_measurement: "A"

      rtu1_cur_total:
        friendly_name: "RTU1 Current total"
        value_template: >-
          {{ states('sensor.rtu1_x108').split(',')[6] | int / 10 }}
        unit_of_measurement: "A"

# EOF
