# (...)

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888

    sensors:
        
      - name: 'RTU Voltage L1'
        slave: 1
        address: 108
        input_type: input
        unit_of_measurement: 'V'
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        data_type: uint

      - name: 'RTU Current L1'
        slave: 1
        address: 109
        input_type: input
        unit_of_measurement: 'A'
        count: 1
        scale: 0.1
        offset: 0
        precision: 1
        data_type: uint

      - name: 'RTU Total Energy'
        slave: 1
        address: 22
        input_type: input
        unit_of_measurement: 'kWh'
        count: 1
        scale: 0.001
        offset: 0
        precision: 1
        data_type: custom
        structure: ">HH"

# (...)
