# (...)

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888

    sensors:
        
      - name: 'RTU Voltage L1'
        slave: 1
        address: 108
        input_type: input
        count: 1
        data_type: uint
        scale: 0.1
        precision: 1
        unit_of_measurement: 'V'

      - name: 'RTU Current L1'
        slave: 1
        address: 109
        input_type: input
        count: 1
        data_type: uint
        scale: 0.1
        precision: 1
        unit_of_measurement: 'A'

      - name: 'RTU X108'
        slave: 1
        address: 108
        input_type: input
        count: 2
        data_type: custom
        structure: ">HH"

sensor rtux1:

  - platform: template
    sensors:
      voltage_l1:
        friendly_name: "RTU X Voltage L1"
        value_template: >-
          "{{ states(rtu_x108)[1:3]|int/10 }}"
        unit_of_measurement: 'V'

# EOF
