# (...)

logger:

  logs:
    homeassistant.components.modbus: debug
    pymodbus.client: debug

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888
    timeout: 5
    delay: 1
  
    sensors:

      - name: "RTU1 X1"
        # 01 # Clock
        slave: 1
        address: 1
        input_type: input
        count: 1
        data_type: custom
        register_size: 12
        structure: ">H7BhB"

      - name: "RTU1 X4"
        # 04-06 # Firmwares
        slave: 1
        address: 4
        input_type: input
        count: 3
        data_type: string
        register_size: 6

      - name: "RTU1 X11"
        # 0B # Tarifa
        slave: 1
        address: 11
        input_type: input
        count: 1
        data_type: custom
        structure: ">Bx"

      - name: "RTU1 X22"
        # 16-17 # Total I/E Kwh
        slave: 1
        address: 22
        input_type: input
        count: 2
        data_type: custom
        register_size: 4
        structure: ">2L"

      - name: "RTU1 X108"
        # 6C-72 # V/A
        slave: 1
        address: 108
        input_type: input
        count: 7
        data_type: custom
        structure: ">7H"

####

# EOF
