# (...)

logger:

  logs:
    homeassistant.components.modbus: debug
    pymodbus.client: debug

modbus:

  - name: edpbox1
    type: rtuovertcp
    host: 10.1.0.40
    port: 8888
    timeout: 5
    delay: 1
  

    sensors:

      - name: "RTU1 Active Tariff"
        slave: 1
        address: 11
        input_type: input
        count: 1
        data_type: custom
        register_size: 2
        structure: ">Bx"

      - name: "RTU1 X108"
        slave: 1
        address: 108
        input_type: input
        count: 7
        data_type: custom
        structure: ">7H"

      - name: "RTU1 X108v"
        slave: 1
        address: 108
        input_type: input
        count: 1
        data_type: uint
        register_size: 2

      - name: "RTU1 Firmware"
        slave: 1
        address: 5
        input_type: input
        count: 1
        data_type: custom
        register_size: 6
        structure: ">6s"

      - name: "RTU1 X22"
        slave: 1
        address: 22
        input_type: input
        count: 1
        data_type: custom
        register_size: 4
        structure: ">L"

      - name: "RTU1 X1"
        slave: 1
        address: 1
        input_type: input
        count: 1
        data_type: custom
        register_size: 12
        structure: ">H7BhB"

# EOF
