sensor:

  - platform: mqtt
    name: "EB ESP Uptime"
    unique_id: eb_esp_uptime
    state_topic: "tele/contador/STATE"
    value_template: '{{ ( value_json.UptimeSec / 3600 ) | round(1) }}'
    unit_of_measurement: "h"
    icon: mdi:alarm

  - platform: mqtt
    name: "EB ESP Signal"
    unique_id: eb_esp_signal
    state_topic: "tele/contador/STATE"
    value_template: '{{ value_json.Wifi.Signal }}'
    unit_of_measurement: "dBm"
    icon: mdi:signal

  - platform: mqtt
    name: "EB Tensão L1"
    unique_id: ebten1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L1|float > 0 %}
        {{ value_json.EB.Voltage_L1|float }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Tensão L2"
    unique_id: ebten2
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L2|float > 0 %}
        {{ value_json.EB.Voltage_L2|float }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Tensão L3"
    unique_id: ebten3
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Voltage_L3|float > 0 %}
        {{ value_json.EB.Voltage_L3|float }}
      {% endif %}
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "EB Corrente L1"
    unique_id: ebcur1
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L1|float }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L2"
    unique_id: ebcur2
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L2|float }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Corrente L3"
    unique_id: ebcur3
    state_topic: "tele/contador/SENSOR"
    value_template: '{{ value_json.EB.Current_L3|float }}'
    unit_of_measurement: "A"
    icon: mdi:power-socket

  - platform: mqtt
    name: "EB Factor de Potência"
    unique_id: ebpfactor
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.PFactor_P1|float > 0.1 %}
        {{ value_json.EB.PFactor_P1|float }}
      {% endif %}
    unit_of_measurement: "p.u."
    icon: mdi:percent
    
  - platform: mqtt
    name: "EB Frequência"
    unique_id: ebfreq
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Frequency_P1|float > 0 %}
        {{ value_json.EB.Frequency_P1|float }}
      {% endif %}
    unit_of_measurement: "Hz"
    icon: mdi:current-ac
    
  - platform: mqtt
    name: "EB Potência Activa"
    unique_id: ebpowerp1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Power_P1|float > 0 %}
        {{ value_json.EB.Power_P1|float }}
      {% endif %}
    unit_of_measurement: "W"
    icon: mdi:power-plug
    
  - platform: mqtt
    name: "EB Vazio T1"
    unique_id: ebenergy1
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_P1_R1|float > 0.1 %}
        {{ value_json.EB.Energy_P1_R1|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Ponta T2"
    unique_id: ebenergy2
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_P1_R2|float > 0.1 %}
        {{ value_json.EB.Energy_P1_R2|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Cheia T3"
    unique_id: ebenergy3
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_P1_R3|float > 0.1 %}
        {{ value_json.EB.Energy_P1_R3|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower

  - platform: mqtt
    name: "EB Consumo Total"
    unique_id: ebenergysum
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Energy_P1_Sum|float > 0.1 %}
        {{ value_json.EB.Energy_P1_Sum|float }}
      {% endif %}
    unit_of_measurement: "kWh"
    icon: mdi:transmission-tower
    
  - platform: mqtt
    name: "EB Tarifa"
    unique_id: ebtariff
    state_topic: "tele/contador/SENSOR"
    value_template: >-
      {% if value_json.EB.Tariff_P1|int == 1 %}
        {{ 'Vazio T1' }}
      {% elif value_json.EB.Tariff_P1|int == 2 %}
        {{ 'Ponta T2' }}
      {% elif value_json.EB.Tariff_P1|int == 3 %}
        {{ 'Cheia T3' }}
      {% else %}
        {{ 'Desconhecida' }}
      {% endif %}
    icon: 'mdi:counter'

