# begin 0x0026

      - id: TotEneT1
        name: "EB1 Total Energy T1"
        address: 0x0026
        offset: 0
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 1000
        unit_of_measurement: "kWh"
        icon: "mdi:transmission-tower"

      - id: TotEneT2
        name: "EB1 Total Energy T2"
        address: 0x0026
        offset: 4
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 1000
        unit_of_measurement: "kWh"
        icon: "mdi:transmission-tower"

      - id: TotEneT3
        name: "EB1 Total Energy T3"
        address: 0x0026
        offset: 8
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 1000
        unit_of_measurement: "kWh"
        icon: "mdi:transmission-tower"

# eof 0x0026
