# begin 0x0016
# filters bug: memory issue esp8266

      - id: TotEneImp
        name: "EB1 Total Energy Import"
        address: 0x0016
        offset: 0
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 1000
        unit_of_measurement: "kWh"
        icon: "mdi:transmission-tower"

      - id: TotEneExp
        name: "EB1 Total Energy Export"
        address: 0x0016
        offset: 4
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 3
        scale_factor: 1000
        unit_of_measurement: "kWh"
        icon: "mdi:transmission-tower"

      - id: TotEneQ1
        name: "EB1 Total Energy Q1"
        address: 0x0016
        offset: 8
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 1000
        unit_of_measurement: "kVAr"
        icon: "mdi:transmission-tower"

# eof 0x0016
