# begin 0x0016
# filters bug: memory issue esp8266

      - id: TotEneImp
        name: "${dev} Total Energy Import"
        address: 0x0016
        offset: 0
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 0.001
        unit_of_measurement: "kWh"
        icon: "mdi:transmission-tower"
        skip_updates: 300

      - id: TotEneExp
        name: "${dev} Total Energy Export"
        address: 0x0016
        offset: 4
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 3
        scale_factor: 0.001
        unit_of_measurement: "kWh"
        icon: "mdi:transmission-tower"

      - id: TotEneQ1
        name: "${dev} Total Energy Q1"
        address: 0x0016
        offset: 8
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 0.001
        unit_of_measurement: "kVAr"
        icon: "mdi:transmission-tower"

      - id: TotEneQ2
        name: "${dev} Total Energy Q2"
        address: 0x0016
        offset: 12
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 0.001
        unit_of_measurement: "kVAr"
        icon: "mdi:transmission-tower"
        internal: true # disable sensor

      - id: TotEneQ3
        name: "${dev} Total Energy Q3"
        address: 0x0016
        offset: 16
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 0.001
        unit_of_measurement: "kVAr"
        icon: "mdi:transmission-tower"
        internal: true # disable sensor

      - id: TotEneQ4
        name: "${dev} Total Energy Q4"
        address: 0x0016
        offset: 20
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        scale_factor: 0.001
        unit_of_measurement: "kVAr"
        icon: "mdi:transmission-tower"

# eof 0x0016
