# begin 0x006C

      - id: VolL1
        name: "EB1 Voltage L1"
        address: 0x006C
        offset: 0
        unit_of_measurement: "V"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        scale_factor: 0.1
        device_class: voltage

      - id: CurL1
        name: "EB1 Current L1"
        address: 0x006C
        offset: 2
        unit_of_measurement: "A"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        scale_factor: 0.1
        device_class: current

      - id: VolL2
        name: "EB1 Voltage L2"
        address: 0x006C
        offset: 4
        unit_of_measurement: "V"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        scale_factor: 0.1
        device_class: voltage

      - id: CurL2
        name: "EB1 Current L2"
        address: 0x006C
        offset: 6
        unit_of_measurement: "A"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        scale_factor: 0.1
        device_class: current

      - id: VolL3
        name: "EB1 Voltage L3"
        address: 0x006C
        offset: 8
        unit_of_measurement: "V"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        scale_factor: 0.1
        device_class: voltage

      - id: CurL3
        name: "EB1 Current L3"
        address: 0x006C
        offset: 10
        unit_of_measurement: "A"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        scale_factor: 0.1
        device_class: current

      - id: Cur
        name: "EB1 Current"
        address: 0x006C
        offset: 12
        unit_of_measurement: "A"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        scale_factor: 0.1
        accuracy_decimals: 1
        device_class: current

# eof 0x006C
