# begin active power

      - id: Active_Power_L1
        name: "EB1 Active Power L1"
        address: 0x0073
        offset: 0
        modbus_functioncode: "read_input_registers"
        value_type: U_LONG
        accuracy_decimals: 0
        device_class: power

      - id: Active_Power_L2
        name: "EB1 Active Power L2"
        address: 0x0073
        offset: 4
        modbus_functioncode: "read_input_registers"
        value_type: U_LONG
        accuracy_decimals: 0
        device_class: power

      - id: Active_Power_L3
        name: "EB1 Active Power L3"
        address: 0x0073
        offset: 8
        unit_of_measurement: "W"
        modbus_functioncode: "read_input_registers"
        value_type: U_LONG
        accuracy_decimals: 0
        device_class: power

      - id: Active_Power_Import
        name: "EB1 Active Power Import"
        address: 0x0073
        offset: 12
        modbus_functioncode: "read_input_registers"
        value_type: U_LONG
        accuracy_decimals: 0
        device_class: power

      - id: Active_Power_Export
        name: "EB1 Active Power Export"
        address: 0x0073
        offset: 14
        modbus_functioncode: "read_input_registers"
        value_type: U_LONG
        accuracy_decimals: 0
        device_class: power

# eof active power
