# begin power factor

      - id: Power_Factor
        name: "EB1 Power Factor"
        address: 0x007B
        offset: 0
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_SINGLE
        filters:
          - multiply: 0.001
        accuracy_decimals: 1
        device_class: power_factor

      - id: Power_Factor_L1
        name: "EB1 Power Factor L1"
        address: 0x007B
        offset: 1
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_SINGLE
        filters:
          - multiply: 0.001
        accuracy_decimals: 1
        device_class: power_factor

      - id: Power_Factor_L2
        name: "EB1 Power Factor L2"
        address: 0x007B
        offset: 2
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_SINGLE
        filters:
          - multiply: 0.001
        accuracy_decimals: 1
        device_class: power_factor

      - id: Power_Factor_L3
        name: "EB1 Power Factor L3"
        address: 0x007B
        offset: 3
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_SINGLE
        filters:
          - multiply: 0.001
        accuracy_decimals: 1
        device_class: power_factor

      - id: Frequency
        name: "EB1 Frequency"
        address: 0x007B
        offset: 4
        unit_of_measurement: "Hz"
        modbus_functioncode: "read_input_registers"
        value_type: U_SINGLE
        filters:
          - multiply: 0.1
        accuracy_decimals: 1

# eof power factor
