substitutions:

  dev: EB1
  name: edpbox1

esphome:

  name: ${name}
  platform: ESP8266
  board: esp01_1m

interval:

  - interval: 7s
    then:
      - lambda: |-
          if (id(boxloop) = 5) {
            id(edpbox_slow).update();
          } else {
            id(edpbox_fast).update();
          }
          if (id(boxloop) > 100) {
          id(boxloop) = 5;
          } else {
          id(boxloop) += 1;
          }

wifi:

  ssid: !secret wifi_ssid
  password: !secret wifi_key
#  ssid: my_wifi
#  password: edpbox123

  ap:
    ssid: "Fallback ${dev}"
    password: edpbox123

captive_portal:

web_server:

  css_url: https://nikito7.github.io/edpbox_v2.css

api:

  password: edpbox123

ota:

  password: edpbox123

globals:

   - id: boxloop
     type: int
     restore_value: no
     initial_value: '0' 

#logger:
#  level: VERBOSE

switch:

  - platform: restart
    name: "${dev} ESP Restart"

uart:

  tx_pin: 5
  rx_pin: 14
  baud_rate: 9600
  stop_bits: 1
  id: edpbox_serial

modbus:

  uart_id: edpbox_serial
  # ctrl_pin: 5
  id: edpbox_bus

sensor:

  - platform: template
    name: "${dev} ESP Free Heap"
    lambda: |-
      int heap = ESP.getFreeHeap();
      return heap / 1024.0;
    unit_of_measurement: "kB"
    update_interval: 5s
    icon: mdi:chip

  - platform: wifi_signal
    name: "${dev} ESP Signal"
    update_interval: 30s

  - platform: uptime
    name: "${dev} ESP Uptime"
    filters:
      - lambda: return x/3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1
    update_interval: 30s

### ### ###

  - platform: modbus_component
    modbus_id: edpbox_bus
    address: 0x1
    command_throttle: 1500 # ms
    update_interval: never
    id: edpbox_fast
    sensors:

### ### ###

# fast sensors polling

### ### ###

  - platform: modbus_component
    modbus_id: edpbox_bus
    address: 0x1
    command_throttle: 1500 # ms
    update_interval: never
    id: edpbox_slow
    sensors:

### ### ###

# slow sensors polling

### ### ### 

#######
# eof #
#######

