substitutions:

  dev: EB5

esphome:

  name: edpbox5esp
  platform: ESP8266
  board: esp01_1m

interval:

  - interval: 9s
    then:
      - lambda: |-
          if (millis() > 15000) {
            id(edpbox5).update();
          }

wifi:

  ssid: edpbox5wifi
  password: edpbox123

  ap:
    ssid: "Fallback ${dev}"
    password: edpbox123

captive_portal:

web_server:

api:

  password: edpbox123

ota:

  password: edpbox123

#logger:
#  level: VERBOSE

switch:

  - platform: restart
    name: "${dev} ESP Restart"

uart:

  tx_pin: 5
  rx_pin: 14
  baud_rate: 9600
  stop_bits: 1
  id: edpbox_serial

modbus:

  uart_id: edpbox_serial
  # ctrl_pin: 5
  id: edpbox_bus

sensor:

  - platform: template
    name: "${dev} ESP Free Heap"
    lambda: |-
      int heap = ESP.getFreeHeap();
      return heap / 1024.0;
    unit_of_measurement: "kB"
    update_interval: 5s
    icon: mdi:chip

  - platform: wifi_signal
    name: "${dev} ESP Signal"
    update_interval: 30s

  - platform: uptime
    name: "${dev} ESP Uptime"
    filters:
      - lambda: return x/3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1
    update_interval: 30s

### ### ###

  - platform: modbus_component
    modbus_id: edpbox_bus
    address: 0x1
    command_throttle: 1000
    update_interval: never
    id: edpbox5
    sensors:

### ### ###

# paste here

### ### ###

#######
# eof #
#######
