substitutions:

  dev: T5

esphome:

  name: *******
  platform: ESP8266
  board: esp01_1m

interval:

  - interval: 9s
    then:
      - lambda: |-
          if (millis() > 15000) {
            id(edpbox1).update();
          }

wifi:

  ssid: !secret wifi_ssid
  password: !secret wifi_key

#  ap:
#    ssid: "Fallback ${dev}"
#    password: !secret wifi_key
#
#captive_portal:
#
#web_server:

api:

  password: !secret api_key

ota:

  password: !secret ota_key

#logger:
#  level: VERBOSE

switch:

  - platform: restart
    name: "${dev} ESP Restart"

uart:

  tx_pin: 5
  rx_pin: 14
  baud_rate: 9600
  stop_bits: 1
  id: edpbox_serial

modbus:

  uart_id: edpbox_serial
  # ctrl_pin: 5
  id: edpbox_bus

sensor:

  - platform: template
    name: "${dev} ESP Free Heap"
    lambda: |-
      int heap = ESP.getFreeHeap();
      return heap / 1024.0;
    unit_of_measurement: "kB"
    update_interval: 5s
    icon: mdi:chip

  - platform: wifi_signal
    name: "${dev} ESP Signal"
    update_interval: 30s

  - platform: uptime
    name: "${dev} ESP Uptime"
    filters:
      - lambda: return x/3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1
    update_interval: 30s

### ### ###

  - platform: modbus_component
    modbus_id: edpbox_bus
    address: 0x1
    command_throttle: 1000
    update_interval: never
    id: edpbox1
    sensors:

### ### ###

# paste here

### ### ###

#######
# eof #
#######
