# (...)

time:

  - platform: homeassistant
    id: esptime

#logger:
#  level: VERBOSE

uart:

  tx_pin: 5
  rx_pin: 14
  baud_rate: 9600
  stop_bits: 1
  id: edpbox_serial

modbus:

  uart_id: edpbox_serial
# ctrl_pin: 5
  id: edpbox_bus


### ### ###

sensor:

  - platform: modbus_component
    modbus_id: edpbox_bus
    address: 0x1
    command_throttle: 1500
    update_interval: 4s
    # min update = (throttle/1000)*(unique_ranges + 1)
    sensors:

### ### ###



### ### ###

#######
# eof #
#######

