# Config for three phase meter.
# ESP32 is recommended!

substitutions:

  dev: EB3
  name: edpbox3

esphome:

  name: ${name}

  #platform: ESP8266
  #board: esp01_1m

  platform: ESP32
  board: esp32dev

wifi:

  domain: .lan
  use_address: 10.1.0.40 # fix ota dns error

  ssid: !secret wifi_ssid
  password: !secret wifi_key
#  ssid: my_wifi
#  password: edpbox123

  ap:
    ssid: "Fallback ${dev}"
    password: edpbox123

captive_portal:

web_server:

#logger:
#  level: verbose

api:

  password: !secret api_key

ota:

  password: !secret ota_key

time:

  - platform: homeassistant
    id: esptime

switch:

  - platform: restart
    name: "${dev} ESP Restart"

uart:

  id: modbus_serial
  rx_pin: 19
  tx_pin: 18
  baud_rate: 9600
  stop_bits: 1

modbus:

  #flow_control_pin: 5
  id: modbus1
  uart_id: modbus_serial

modbus_controller:

  - id: edpbox
    update_interval: 9s
    address: 0x1
    command_throttle: 1s
    setup_priority: -10

sensor:

  - platform: template
    name: "${dev} ESP Free Heap"
    lambda: |-
      int heap = ESP.getFreeHeap();
      return heap / 1024.0;
    unit_of_measurement: "kB"
    update_interval: 30s
    icon: mdi:chip

  - platform: wifi_signal
    name: "${dev} ESP Signal"
    unit_of_measurement: "dBm"
    update_interval: 30s

  - platform: uptime
    name: "${dev} ESP Uptime"
    filters:
      - lambda: return x/3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

### Active Power

  - platform: modbus_controller
    name: "${dev} Active Power L1"
    address: 0x0073
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: "W"

  - platform: modbus_controller
    name: "${dev} Active Power L1 Export"
    address: 0x0074
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: "W"
    internal: true # disable sensor

  - platform: modbus_controller
    name: "${dev} Active Power L2"
    address: 0x0075
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: "W"

  - platform: modbus_controller
    name: "${dev} Active Power L2 Export"
    address: 0x0076
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: "W"
    internal: true # disable sensor

  - platform: modbus_controller
    name: "${dev} Active Power L3"
    address: 0x0077
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: "W"

  - platform: modbus_controller
    name: "${dev} Active Power L3 Export"
    address: 0x0078
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: "W"
    internal: true # disable sensor

  - platform: modbus_controller
    name: "${dev} Active Power"
    address: 0x0079
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: "W"

  - platform: modbus_controller
    name: "${dev} Active Power Export"
    address: 0x007A
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: "W"
    internal: true # disable sensor

### Total Energy Tariffs

  - platform: modbus_controller
    name: "${dev} T1 Vazio"
    address: 0x0026
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy

  - platform: modbus_controller 
    name: "${dev} T2 Ponta"
    address: 0x0027
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy

  - platform: modbus_controller
    name: "${dev} T3 Cheias"
    address: 0x0028
    register_type: read
    value_type: U_DWORD
    register_count: 1
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: total_increasing
    device_class: energy

#######
# eof #
#######
