


# type changes ####

      - id: PowFac
        name: "${dev} Power Factor"
        address: 0x007B
        offset: 32
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 3
        filters:
          - multiply: 0.001
        device_class: power_factor

      - id: PowFacL1
        name: "${dev} Power Factor L1"
        address: 0x007C
        offset: 34
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 3
        filters:
          - multiply: 0.001
        device_class: power_factor

      - id: PowFacL2
        name: "${dev} Power Factor L2"
        address: 0x007D
        offset: 36
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 3
        filters:
          - multiply: 0.001
        device_class: power_factor

      - id: PowFacL3
        name: "${dev} Power Factor L3"
        address: 0x007E
        offset: 38
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 3
        filters:
          - multiply: 0.001
        device_class: power_factor

      - id: Freq
        name: "${dev} Frequency"
        address: 0x007F
        offset: 40
        unit_of_measurement: "Hz"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        filters:
          - multiply: 0.1
        icon: "mdi:pulse"

# eof 0x0073

###
      - id: TotEneImp
        name: "${dev} Total Energy Import"
        address: 0x0016
        offset: 0
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 1
        filters:
          - multiply: 0.001
        unit_of_measurement: "kWh"
        state_class: measurement
        device_class: energy
        last_reset_type: auto

      - id: TotEneExp
        name: "${dev} Total Energy Export"
        address: 0x0017
        offset: 4
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 3
        filters:
          - multiply: 0.001
        unit_of_measurement: "kWh"
        state_class: measurement
        device_class: energy
        last_reset_type: auto


# eof 0x0016


        

text_sensor:

      - id: EBX1
        name: "${dev} 0x0001 Clock" 
        modbus_functioncode: "read_input_registers" 
        address: 0x0001
        offset: 0
        register_count: 1
        raw_encode: COMMA
        response_size: 12
        icon: mdi:chip

      - id: EBX4
        name: "${dev} Info: Firmware Core" 
        modbus_functioncode: "read_input_registers" 
        address: 0x0004
        offset: 0
        register_count: 1
        raw_encode: NONE
        response_size: 6
        icon: mdi:chip
        skip_updates: 23

      - id: EB_Tariff
        name: "${dev} 0x000B Tariff"
        modbus_functioncode: "read_input_registers"
        address: 0x000B
        offset: 0
        register_count: 1
        raw_encode: COMMA
        response_size: 2
        icon: mdi:chip

      - id: EBDCP
        name: "${dev} 0x0084 DCP"
        modbus_functioncode: "read_input_registers" 
        address: 0x0084
        offset: 0
        register_count: 1
        raw_encode: COMMA
        response_size: 2
        icon: mdi:chip

#######
# eof #
#######
