# Config for three phase meter.
# ESP32 is recommended!

substitutions:

  dev: EB9
  name: edpbox9

esphome:

  name: ${name}

  #platform: ESP8266
  #board: esp01_1m

  platform: ESP32
  board: esp32dev

wifi:

  domain: .lan

  ssid: !secret wifi_ssid
  password: !secret wifi_key
#  ssid: my_wifi
#  password: edpbox123

  ap:
    ssid: "Fallback ${dev}"
    password: edpbox123

captive_portal:

web_server:

logger:
  level: verbose

api:

  password: !secret api_key

ota:

  password: !secret ota_key

time:

  - platform: homeassistant
    id: esptime

switch:

  - platform: restart
    name: "${dev} ESP Restart"

uart:

  id: modbus_serial
  rx_pin: 19 # from tasmota, first rx
  tx_pin: 18
  baud_rate: 9600
  stop_bits: 1

modbus:

  #flow_control_pin: 5
  id: modbus1
  uart_id: modbus_serial

modbus_controller:

  - id: edpbox3
    modbus_id: modbus1
    update_interval: 9s
    address: 0x1

sensor:

  - platform: template
    name: "${dev} ESP Free Heap"
    lambda: |-
      int heap = ESP.getFreeHeap();
      return heap / 1024.0;
    unit_of_measurement: "kB"
    update_interval: 30s
    icon: mdi:chip

  - platform: wifi_signal
    name: "${dev} ESP Signal"
    update_interval: 30s

  - platform: uptime
    name: "${dev} ESP Uptime"
    filters:
      - lambda: return x/3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

### ### ###

  - platform: modbus_controller
    name: "${dev} T1 Vazio"
    address: 0x0026
    offset: 0
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    last_reset_type: auto

  - platform: modbus_controller
    name: "${dev} T2 Ponta"
    address: 0x0026
    offset: 2
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    last_reset_type: auto

  - platform: modbus_controller
    name: "${dev} T3 Cheias"
    address: 0x0026
    offset: 4
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    last_reset_type: auto

### ### ###

text_sensor:

  - platform: modbus_controller
    name: "${dev} 0x0001 Clock" 
    modbus_functioncode: "read_input_registers" 
    address: 0x0001
    offset: 0
    raw_encode: COMMA
    response_size: 12
    icon: mdi:chip

  - platform: modbus_controller 
    name: "${dev} Info: Firmware Core" 
    modbus_functioncode: "read_input_registers" 
    address: 0x0004
    offset: 0
    raw_encode: NONE
    response_size: 6
    icon: mdi:chip

#######
# eof #
#######
