# esphome eb3 package

sensor:

  - platform: template
    sensors:

      eb3_dcp:
        friendly_name: "EB3 DCP"
        unique_id: eb3_dcp
        value_template: >-
          {% set x = states('sensor.eb3_0x0084_dcp').split(',')[0]|string %}
          {% if x == "0" or x == "1" or x == "2" %}
            {{ x }}
          {% endif %}
        icon_template: mdi:chip

      eb3_tariff:
        friendly_name: "EB3 Tariff"
        unique_id: eb3_tariff
        value_template: >-
          {% set x = states('sensor.eb3_0x000B_tariff').split(',')[0]|string %}
          {% if x == "1" %}
            {{ "Vazio" }}
          {% elif x == "2" %}
            {{ "Ponta" }}
          {% elif x == "3" %}
            {{ "Cheias" }}
          {% endif %}
        icon_template: mdi:calendar

# EOF
