sensor eb1esphm:

  - platform: template
    sensors:

      eb1_clock_time:
        friendly_name: "EB1 Clock Time"
        value_template: >-
          {% set hh = states('sensor.eb1_x1_clock').split(',')[5] %}
          {% set mm = states('sensor.eb1_x1_clock').split(',')[6] %}
          {% set ss = states('sensor.eb1_x1_clock').split(',')[7] %}
          {{ '{0:02d}'.format(hh) + ":" + '{0:02d}'.format(mm) + ":" + '{0:02d}'.format(ss) }}
        icon_template: mdi:clock

# EOF
