sensor eb1esphm:

  - platform: template
    sensors:

      eb1_clock_time:
        friendly_name: "EB1 Clock Time"
        value_template: >-
          {% set hh = states('sensor.eb1_x1_clock').split(',')[5]|int %}
          {% set mm = states('sensor.eb1_x1_clock').split(',')[6]|int %}
          {% set ss = states('sensor.eb1_x1_clock').split(',')[7]|int %}
          {{ '{0:02d}'.format(hh) + ":" + '{0:02d}'.format(mm) + ":" + '{0:02d}'.format(ss) }}
        icon_template: mdi:clock

      eb1_clock_date:
        friendly_name: "EB1 Clock Date"
        value_template: >-
          {% set yy = states('sensor.eb1_x1_clock').split(',')[0:3]|join(',')|int %}
          {% set mm = states('sensor.eb1_x1_clock').split(',')[3]|int %}
          {% set dd = states('sensor.eb1_x1_clock').split(',')[4]|int %}
          {{ yy + "-" + '{0:02d}'.format(mm) + "-" + '{0:02d}'.format(dd) }}
        icon_template: mdi:clock

# EOF
