sensor eb1esphm:

  - platform: template
    sensors:

      eb1_clock:
        friendly_name: "EB1 Clock"
        value_template: >-
          {% set hh = states('sensor.eb1_0x0001_clock').split(',')[5]|int %}
          {% set mm = states('sensor.eb1_0x0001_clock').split(',')[6]|int %}
          {% set ss = states('sensor.eb1_0x0001_clock').split(',')[7]|int %}
          {{ '{0:02d}'.format(hh) + ":" + '{0:02d}'.format(mm) + ":" + '{0:02d}'.format(ss) }}
        icon_template: mdi:clock

# EOF
