# sensor eb1esphm: !include esphome_eb1.yaml

  - platform: template
    sensors:

      eb1_clock:
        friendly_name: "EB1 Clock"
        unique_id: eb1_clock
        value_template: >-
          {% if states('sensor.eb1_0x0001_clock').split(',')[5] %}
            {% set hh = states('sensor.eb1_0x0001_clock').split(',')[5]|int %}
            {% set mm = states('sensor.eb1_0x0001_clock').split(',')[6]|int %}
            {% set ss = states('sensor.eb1_0x0001_clock').split(',')[7]|int %}
            {{ '{0:02d}'.format(hh) + ":" + '{0:02d}'.format(mm) + ":" + '{0:02d}'.format(ss) }}
          {% endif %}
        icon_template: mdi:clock

# EOF
