sensor eb1esphm:

  - platform: template
    sensors:

      eb1_clock_time:
        friendly_name: "EB1 Clock Time"
        value_template: >-
          {% set hh = states('sensor.eb1_x1_clock').split(',')[5]|int %}
          {% set mm = states('sensor.eb1_x1_clock').split(',')[6]|int %}
          {% set ss = states('sensor.eb1_x1_clock').split(',')[7]|int %}
          {{ '{0:02d}'.format(hh) + ":" + '{0:02d}'.format(mm) + ":" + '{0:02d}'.format(ss) }}
        icon_template: mdi:clock

      eb1_clock_date:
        friendly_name: "EB1 Clock Date"
        value_template: >-
          {% set ya = states('sensor.eb1_x1_clock').split(',')[1] %}
          {% set yb = states('sensor.eb1_x1_clock').split(',')[2] %}
          {% set yc = ya|int(ya,16) + yb|int(yb,16) %}
          {% set yd = yc|int(yc,2) %}
          {% set d = states('sensor.eb1_x1_clock').split(',')[3]|int %}
          {% set e = states('sensor.eb1_x1_clock').split(',')[4]|int %}
          {{ yd + "-" + '{0:02d}'.format(d) + "-" + '{0:02d}'.format(e) }}
        icon_template: mdi:calendar

# EOF
