sensor eb1esphm:

  - platform: template
    sensors:

      eb1_clock_date:
        friendly_name: "EB1 Clock Date"
        value_template: >-
          {% set x = states('sensor.eb1_x1_clock')[0:3] %}
          {% set y = states('sensor.eb1_x1_clock')[4] %}
          {% set z = states('sensor.eb1_x1_clock')[5] %}
          {{ x + y + z }}
        icon_template: mdi:calendar

      eb1_clock_time:
        friendly_name: "EB1 Clock Time"
        value_template: >-
          {% set hh = states('sensor.eb1_x1_clock')[7] %}
          {% set mm = states('sensor.eb1_x1_clock')[8] %}
          {% set ss = states('sensor.eb1_x1_clock')[9] %}
          {{ hh + mm + ss }}
        icon_template: mdi:clock

# EOF
