# sensor eb1esphm: !include esphome_eb1.yaml

  - platform: template
    sensors:

      eb1_clock:
        friendly_name: "EB1 Clock"
        unique_id: eb1_clock
        value_template: >-
          {% set hh = states('sensor.eb1_0x0001_clock').split(',')[5]|int %}
          {% set mm = states('sensor.eb1_0x0001_clock').split(',')[6]|int %}
          {% set ss = states('sensor.eb1_0x0001_clock').split(',')[7]|int %}
          {{ '{0:02d}'.format(hh) + ":" + '{0:02d}'.format(mm) + ":" + '{0:02d}'.format(ss) }}
        icon_template: mdi:clock

      eb1_dcp:
        friendly_name: "EB1 DCP"
        unique_id: eb1_dcp
        value_template: >-
          {% set x = states('sensor.eb1_0x0084_dcp').split(',')[0]|int %}
          {{ "S" + x }}
        icon_template: mdi:chip

      eb1_tariff:
        friendly_name: "EB1 Tariff"
        unique_id: eb1_tariff
        value_template: >-
          {% set x = states('sensor.eb1_0x000B_tariff').split(',')[0]|int %}
          {{ "T" + x }}
        icon_template: mdi:chip

# EOF
