# begin test

    text_sensors:

      - id: en1_test
        name: "eb1 test"
        modbus_functioncode: 0x4
        address: 0x0001
        offset: 0
        register_count: 1
        hex_encode: true
        response_size: 10

# eof test
