# begin test

    text_sensors:

      - id: Clock_Test
        name: "EB1 Test 2"
        modbus_functioncode: "read_input_registers"
        address: 0x0001
        offset: 0
        hex_encode: true

# eof test
